# Labels: bug, enhancement, documentation or docs or doc, noadd
# .github/release.yml
changelog:
  exclude:
    labels:
      - noadd
  categories:
    - title: Breaking Changes
      labels:
        - break
    - title: Bug fixes
      labels:
        - bug
    - title: New Features
      labels:
        - enhancement
    - title: Documentation
      labels:
        - documentation
        - docs
        - doc
    - title: Miscellaneous
      labels:
        - "*"