# The language's name
name = "English"
acc_skip_main = "Skip to main content"
acc_skip_nav = "Skip to navigation"
acc_skip_footer = "Skip to footer"
main_menu = "Main menu"
author = "Author"
authors = "authors"
updated = "Updated on: %date%"
lastmod = "Last modified: %l% ago"
readtime = "Reading time: %r%"
published = "Published on: %date%"
wordcount = "Total words: %count%"
pagination_title = "Pagination"
pagination_first = "First page"
pagination_previous = "Previous page"
pagination_next = "Next page"
pagination_last = "Last page"
nav1 = "Home"
nav2 = "Documentation"
nav3 = "Blog"
search_title = "Search the site"
search_result = "%r% results"
search_result_title = "Search results"