name="English"
acc_skip_main="Skip to main content"
acc_skip_nav="Skip to navigation"
acc_skip_footer="Skip to footer"
main_menu="Main menu"
author="Author"
authors="authors"
updated="Updated on: $date$"
published="Published on: $date$"
wordcount="Total words: $count$"
pagination_title="Pagination"
pagination_first="First page"
pagination_previous="Previous page"
pagination_next="Next page"
pagination_last="Last page"
nav1="Home"
nav2="Blog"