name: Zola on GitHub Pages

on:
  push:
    paths: ["content/**", "static/**", "langs/**", "templates/**", "config.toml"]
    branches: [main]
  pull_request:
    paths: ["content/**", "static/**", "langs/**", "templates/**", "config.toml"]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event_name != 'push' && github.event_name != 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build only
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          BUILD_ONLY: true
          BUILD_FLAGS: --drafts

  build_and_deploy:
    runs-on: ubuntu-latest
    if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Build and deploy
        uses: shalzz/zola-deploy-action@v0.19.2
        env:
          PAGES_BRANCH: gh-pages
          OUT_DIR: HTML
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}