name: Deploy Website

on:
  push:
    paths: ["content/**", "static/**", "langs/**", "templates/**", "config.toml"]
    branches: [main]
  pull_request:
    paths: ["content/**", "static/**", "langs/**", "templates/**", "config.toml"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Download and install
        run: |
          $weburl = "https://github.com/getzola/zola/releases/download/v0.19.2/zola-v0.19.2-x86_64-pc-windows-msvc.zip"
          Invoke-WebRequest -Uri $weburl -OutFile "webfile.zip"
          Expand-Archive webfile.zip -DestinationPath "webfile"
          echo "$PWD\webfile" | Out-File -FilePath $env:GITHUB_PATH -Encoding utf8
        shell: pwsh

      - name: Build the site
        run: zola build

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: HTML
