name: Deploy Website

on:
  push:
    paths: ["content/**", "static/**", "langs/**", "templates/**", "config.toml"]
    branches: [main]
  pull_request:
    paths: ["content/**", "static/**", "langs/**", "templates/**", "config.toml"]
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: windows-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install winget
        uses: Cyberboss/install-winget@v1
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          wget_release_id: latest
      - name: Install Zola
        run: |
          winget install getzola.zola
      - name: Build the site
        run: zola build

      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: HTML
