name: Deploy Website
on:
  push:
    paths: ["content/**", "static/**", "langs/**", "templates/**", "config.toml"]
    branches: [main]
  pull_request:
    paths: ["content/**", "static/**", "langs/**", "templates/**", "config.toml"]
  workflow_dispatch:
jobs:
  build-and-deploy:
    runs-on: windows-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - name: Install Zola
        uses: taiki-e/install-action@zola
      - name: Build the site
        run: zola build
      - name: Deploy to GitHub Pages
        if: github.event_name == 'push' || github.event_name == 'workflow_dispatch'
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: HTML